<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseAppHost>false</UseAppHost>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
    <Compile Remove="artifacts\\**\\*.cs" />
    <Content Remove="appsettings*.json" />
    <Content Remove="artifacts\\**" />
    <None Remove="appsettings*.json" />
    <None Remove="artifacts\\**" />
    <Content Include="..\\TasteBudz.Database\\sqlite\\dbTasteBudz.sqlite.sql" Link="DatabaseScripts\\sqlite\\dbTasteBudz.sqlite.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\\TasteBudz.Database\\sqlite\\dbTasteBudz.sqlite.seed.sql" Link="DatabaseScripts\\sqlite\\dbTasteBudz.sqlite.seed.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\\TasteBudz.Database\\sqlite\\dbTasteBudz.sqlite.testdata.sql" Link="DatabaseScripts\\sqlite\\dbTasteBudz.sqlite.testdata.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
